# Generated by Django 3.2.6 on 2021-08-23 16:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='resiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMois', models.IntegerField(default=0)),
                ('redTableau', models.BigIntegerField(blank=True, default=0)),
                ('frais_coupure', models.IntegerField(default=0)),
                ('frais_retard', models.IntegerField(default=0)),
                ('tva', models.DecimalField(decimal_places=2, default=0, max_digits=7, max_length=20)),
                ('timbre', models.DecimalField(decimal_places=2, default=0, max_digits=7, max_length=20, null=True)),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=7, max_length=50)),
                ('montant_a_payer', models.DecimalField(decimal_places=2, default=0, max_digits=7, max_length=50)),
                ('contrat', models.CharField(max_length=25, unique=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
