# Generated by Django 3.2.6 on 2021-08-25 12:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scl', '0002_alter_resiliation_nombremois'),
    ]

    operations = [
        migrations.CreateModel(
            name='affaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrat', models.CharField(max_length=25)),
                ('libelle_affaire', models.CharField(choices=[('Compteur endommagé', 'Compteur endommagé'), ('Chéque vide', 'Chéque vide'), ('Fraude', 'Fraude'), ('Surcharge', 'Surcharge')], default='Fraude', max_length=30)),
                ('description_affaire', models.TextField(blank=True, max_length=100, null=True)),
                ('technicien', models.CharField(max_length=50, null=True)),
                ('montant', models.DecimalField(decimal_places=0, default=0, max_digits=7, max_length=50, null=True)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
