# Generated by Django 3.2.6 on 2021-08-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scl', '0003_affaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affaire',
            name='technicien',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
