# Generated by Django 3.2.6 on 2021-08-25 13:07

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scl', '0004_alter_affaire_technicien'),
    ]

    operations = [
        migrations.AddField(
            model_name='affaire',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='manuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif_reglement', models.CharField(max_length=50)),
                ('contrat', models.CharField(blank=True, max_length=25, null=True)),
                ('mode_payement', models.CharField(blank=True, choices=[('Espéces', 'Espéces'), ('Chéque', 'Chéque')], max_length=30, null=True)),
                ('village', models.CharField(blank=True, max_length=50)),
                ('montant', models.DecimalField(decimal_places=0, default=0, max_digits=7, max_length=50, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
