# Generated by Django 3.2.6 on 2021-08-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scl', '0005_auto_20210825_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuel',
            name='contact_client',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='manuel',
            name='nom_client',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
