# Generated by Django 3.2.6 on 2021-08-27 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scl', '0006_auto_20210825_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resiliation',
            old_name='nombreMois',
            new_name='nombre_mois',
        ),
    ]
