# Generated by Django 3.2.6 on 2021-09-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scl', '0007_rename_nombremois_resiliation_nombre_mois'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resiliation',
            name='montant_a_payer',
            field=models.IntegerField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='resiliation',
            name='montant_ttc',
            field=models.IntegerField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='resiliation',
            name='timbre',
            field=models.IntegerField(default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='resiliation',
            name='tva',
            field=models.IntegerField(default=0, max_length=20),
        ),
    ]
