# Generated by Django 3.2.6 on 2021-09-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scl', '0010_alter_manuel_montant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affaire',
            name='montant',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='manuel',
            name='montant',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='resiliation',
            name='montant_a_payer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resiliation',
            name='montant_ttc',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resiliation',
            name='timbre',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='resiliation',
            name='tva',
            field=models.IntegerField(default=0),
        ),
    ]
