# Generated by Django 3.2.6 on 2021-09-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scl', '0011_auto_20210902_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resiliation',
            name='nombre_mois',
            field=models.IntegerField(default=0),
        ),
    ]
