# Generated by Django 3.2.6 on 2021-09-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scl', '0012_alter_resiliation_nombre_mois'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resiliation',
            name='montant_a_payer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, max_length=50),
        ),
        migrations.AlterField(
            model_name='resiliation',
            name='montant_ttc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, max_length=50),
        ),
        migrations.AlterField(
            model_name='resiliation',
            name='nombre_mois',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resiliation',
            name='timbre',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='resiliation',
            name='tva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, max_length=20),
        ),
    ]
