# Generated by Django 3.2.6 on 2021-09-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scl', '0013_auto_20210903_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resiliation',
            name='montant_a_payer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resiliation',
            name='montant_ttc',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resiliation',
            name='timbre',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='resiliation',
            name='tva',
            field=models.IntegerField(default=0),
        ),
    ]
